# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Prints Perlin noise to file.
#' 
#' @param nOctaves Number of octaves. May be thought of as small scale 
#' variability. Must be an integer value between 1 and 8. Higher values
#' result in landscapes with more small scale noise.
#' @param frequency Frequency of noise. May be thought of as large scale
#' variability. May be any double value between 1.0 and 16.0. Higher values
#' result in noise that is closer to white noise.
#' @param landSize Landscape size in pixels. The image saved will be a
#' square with this side.
#' @param isWrapped A boolean value indicating whether the landscape is
#' tiled, that is, whether the pattern repeats. Useful when generating
#' landscapes for simulations.
#' @param outputPath A string specifying the image file to write the landscape.
#' @return Nothing. Writes an image to file.
getPerlin <- function(nOctaves, frequency, landSize, isWrapped, outputPath) {
    invisible(.Call('_proclandr_getPerlin', PACKAGE = 'proclandr', nOctaves, frequency, landSize, isWrapped, outputPath))
}

rcpp_hello_world <- function() {
    .Call('_proclandr_rcpp_hello_world', PACKAGE = 'proclandr')
}

